arctic_animals = ["penguin", "elephant", "polar bear", "walrus", "tiger", "reindeer"]
del arctic_animals[4]
print(arctic_animals)
arctic_animals.remove("elephant")
print(arctic_animals)
arctic_animals.append("arctic fox")
print(arctic_animals)
arctic_animals.insert(2, "snowy owl")
print(arctic_animals)
arctic_animals.sort()
print(arctic_animals)
some_index = arctic_animals.index("snowy owl")
print(some_index)
arctic_animals.pop()
print(arctic_animals)